name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress UI Testing
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --browser chrome
      - name: Create a mochawesome report
        run: |
          if [ -f "cypress/screenshots/*.png" ]; then
            echo "Tests failed. Creating Mochawesome report..."
            npm install --save-dev mochawesome mochawesome-merge mochawesome-report-generator
            npx mochawesome-merge cypress/reports/mocha/*.json > merged-report.json
            npx mochawesome-report-generator merged-report.json --reportDir cypress/reports/mochawesome
          fi

      # Upload the Mochawesome report as artifact if tests failed
      - name: Upload Mochawesome Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome_report
          path: cypress/reports/html/